language: java
sudo: required
before_install:
      - sudo apt-get update
      - sudo apt-get -y --fix-missing install npm
      - sudo npm config set strict-ssl false
      - sudo npm install -g n
      - sudo n stable
install:      
      - sudo npm uninstall -g yarn
      - sudo npm install -g yarn
jobs:
  include:
    - stage: 'Install Chrome'
      name: 'Install Chrome'
      script: 
            - apt-get update
            - apt-get -y -f install
            - apt-get install wget
            - apt-get -y install libgconf2-4 libnss3-1d libxss1
            - umount /dev/shm
            - mount -t tmpfs -o rw,nosuid,nodev,noexec,relatime,size=512M tmpfs /dev/shm
            - export CHROME_BIN=/usr/bin/google-chrome


