language: java
sudo: required
before_install:
      sudo apt-get update
      sudo apt-get -y --fix-missing install npm
      sudo npm install -g n
      sudo n stable
install:      
      sudo npm uninstall -g yarn
      sudo npm install -g yarn
script: ant main